config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :bookings, only: [:show]
  end
  resources :notdogs do
    resources :bookings, only: [:new, :create]
    resources :messages, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [ :new, :create ]
  end
    get "my_notdogs", to: "notdogs#my_notdogs"
    get "my_booked", to: "bookings#my_booked"

    # buttons to accept/decline a booking
    # get "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    # get "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
    put "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    put "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
end

#               root GET    /                                                  pages#home
#    notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)             bookings#create
# new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)         bookings#new
#    notdog_messages POST   /notdogs/:notdog_id/messages(.:format)             messages#create
# new_notdog_message GET    /notdogs/:notdog_id/messages/new(.:format)         messages#new
# edit_notdog_message GET    /notdogs/:notdog_id/messages/:id/edit(.:format)   messages#edit
#            notdogs GET    /notdogs(.:format)                                 notdogs#index
#                    POST   /notdogs(.:format)                                 notdogs#create
#         new_notdog GET    /notdogs/new(.:format)                             notdogs#new
#        edit_notdog GET    /notdogs/:id/edit(.:format)                        notdogs#edit
#             notdog GET    /notdogs/:id(.:format)                             notdogs#show
#                    PATCH  /notdogs/:id(.:format)                             notdogs#update
#                    PUT    /notdogs/:id(.:format)                             notdogs#update
#                    DELETE /notdogs/:id(.:format)                             notdogs#destroy
#           bookings GET    /bookings(.:format)                                bookings#index
#       edit_booking GET    /bookings/:id/edit(.:format)                       bookings#edit
#            booking GET    /bookings/:id(.:format)                            bookings#show
#                    PATCH  /bookings/:id(.:format)                            bookings#update
#                    PUT    /bookings/:id(.:format)                            bookings#update


#                   Prefix Verb   URI Pattern                                  Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                     devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                    devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)               devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                    devise/passwords#update
#                          PUT    /users/password(.:format)                    devise/passwords#update
#                          POST   /users/password(.:format)                    devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                      devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                     devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                        devise/registrations#edit
#        user_registration PATCH  /users(.:format)                             devise/registrations#update
#                          PUT    /users(.:format)                             devise/registrations#update
#                          DELETE /users(.:format)                             devise/registrations#destroy
#                          POST   /users(.:format)                             devise/registrations#create
#                     root GET    /                                            pages#home
#          notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)       bookings#create
#       new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)   bookings#new
#                  notdogs GET    /notdogs(.:format)                           notdogs#index
#                          POST   /notdogs(.:format)                           notdogs#create
#               new_notdog GET    /notdogs/new(.:format)                       notdogs#new
#              edit_notdog GET    /notdogs/:id/edit(.:format)                  notdogs#edit
#                   notdog GET    /notdogs/:id(.:format)                       notdogs#show
#                          PATCH  /notdogs/:id(.:format)                       notdogs#update
#                          PUT    /notdogs/:id(.:format)                       notdogs#update
#                          DELETE /notdogs/:id(.:format)                       notdogs#destroy
#                 bookings GET    /bookings(.:format)                          bookings#index
#             edit_booking GET    /bookings/:id/edit(.:format)                 bookings#edit
#                  booking GET    /bookings/:id(.:format)                      bookings#show
#                          PATCH  /bookings/:id(.:format)                      bookings#update
#                          PUT    /bookings/:id(.:format)                      bookings#update
#          booking_reviews POST   /bookings/:booking_id/reviews(.:format)      reviews#create
#       new_booking_review GET    /bookings/:booking_id/reviews/new(.:format)  reviews#new

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :notdog
  belongs_to :user
  has_one :owner, through: :notdog
  has_many :reviews
  validates :notdog, :start_date, :end_date, :user, presence: true
  validate :start_date_lower_than_end_date
  validate :start_date_lower_than_today
  # validate :notdog_booked

  def start_date_lower_than_end_date
    if start_date > end_date
      errors.add(:start_date, "no puede ser mayor que la fecha final")
    end
  end

  def start_date_lower_than_today
    if Date.today > start_date
      errors.add(:start_date, "no puede ser en el pasado, Marty!")
    end
  end

  def notdog_booked
    start_date = self.start_date.beginning_of_day
    end_date = self.end_date.end_of_day
    if Booking.where(notdog_id: self.notdog_id).where('start_date BETWEEN ? AND ?', start_date, end_date).where('end_date BETWEEN ? AND ?', start_date, end_date).present?
      errors.add(:start_date, "el Notdog ya está reservado en esas fechas!")
    end
    #if !Booking.where(:start_date => start_date..end_date, :end_date => start_date..end_date, :notdog_id => self.notdog_id).empty?
    #  errors.add(:start_date, "el Notdog ya está reservado en esas fechas!")
    #end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only: [:my_booked]


  def index
    @bookings = policy_scope(Booking).order(created_at: :asc)
  end

  def show
    @markers =
    [{
      lat: @booking.notdog.latitude,
      lng: @booking.notdog.longitude,
        # infoWindow: render_to_string(partial: "info_window", locals: { notdog: @notdog }),
      image_url: helpers.asset_url('notdog-marker.png')
      }]
  end

  def new
    @booking = Booking.new
    @notdog = Notdog.find(params[:notdog_id].to_i)
    @booking.notdog = @notdog
    authorize @notdog
    authorize @booking
  end

  def create
    @booking = Booking.new(start_date: booking_params[:start_date].split[0], end_date: booking_params[:start_date].split[2])
    @booking.user = current_user
    @booking.notdog = Notdog.find(params[:notdog_id])
    @notdog = Notdog.find(params[:notdog_id])
    @booking.price = @booking.notdog.cost_per_day * (@booking.end_date - @booking.start_date)
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :show
    end
  end

  def my_booked
    @notdogs = current_user.notdogs
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    @booking.update(status: "accepted")
    redirect_to my_booked_path
  end

  def decline
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    @booking.update(status: "declined")
    redirect_to my_booked_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :notdog, :user, :price)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/views/bookings/_new_booking_form.html.erb
<div class="container form-container">
  <div class="form-wrapper" style="margin: 0 auto;">
       <h2 class="orange form-header">Book this Notdog now!</h2>
    <%= simple_form_for([ @notdog, @booking ]) do |f| %>
      <%= f.input :start_date, as: :string, label: "Date Range", input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Reserve", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="d-none booking-new">
    <% @notdog.bookings.each do |booking| %>
      <div id="invalid-dates">
        <%= booking.start_date %> - <%= booking.end_date %>
      </div>
    <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h1 class="main-header">My bookings</h1>
    <% @bookings.each do |booking| %>
      <div class="card-booking mb-3">
        <img src=<%= cl_image_path booking.notdog.photo.key, height: 500, width: 700, crop: :fill %> >
          <div class="card-booking-infos">
            <div>
                <p class="text-black-50"><%= booking.notdog.taxonomy_fantasy_name %> (<%= booking.notdog.taxonomy_name %>)</p>
                <h2><%= link_to booking.notdog.name, notdog_path(booking.notdog) %></h2>
                <p><%= booking.start_date %> - <%= booking.end_date %></p>
                <p><%= booking.notdog.address  %></p>
                <p class=>USD$<%= booking.price %></p>
                <!-- Accept/Decline booking -->
                <% case booking.status %>
                <% when "pending" %>
                <p style="color: #e59500; font-weight: bolder">Pending response from <%= booking.owner.name %></p>
                <% when "accepted" %>
                <p style="color: green; font-weight: bolder">Accepted</p>
                <% when "declined" %>
                <p style="color: red; font-weight: bolder">Declined</p>
                <% end %>
                <hr>
                <%= link_to "See booking", booking_path(booking), class: "see-booking" %>
              </div>
        </div>
    </div>
   <% end %>
</div>

app/views/bookings/my_booked.html.erb
<div class="container mt-5">
  <h1 class="main-header">My booked NotDogs</h1>
  <div class='row'>
    <% @notdogs.each do |notdog| %>
      <% notdog.bookings.each do |booking| %>
        <div class="col-12">
          <div class="card-booking my-3">
              <img src=<%= cl_image_path booking.notdog.photo.key, height: 500, width: 700, crop: :fill %> >

          <div class='row'>
            <div class='col-7'>
              <div class="card-booking-infos">
                <div>
                  <p class="text-black-50"><%= booking.notdog.taxonomy_fantasy_name %> (<%= booking.notdog.taxonomy_name %>)</p>
                  <h2><%= link_to booking.notdog.name, notdog_path(booking.notdog) %></h2>
                  <p><%= booking.start_date %> - <%= booking.end_date %></p>
                  <p><%= booking.notdog.address  %></p>
                  <p class=>USD$<%= booking.price %></p>
                  <%= link_to "See booking", booking_path(booking) %>
                    <!-- Accept/Decline booking -->
                    <% case booking.status %>
                    <% when "pending" %>
                      <p style="color: #e59500; font-weight: bolder">Pending response from <%= booking.owner.name %></p>
                      <%= link_to "Accept", accept_path(booking), method: :put, remote: true, class:"btn btn-success" %>
                      <%= link_to "Decline", decline_path(booking), method: :put, remote: true, class:"btn btn-danger" %>
                    <% when "accepted" %>
                      <p style="color: green; font-weight: bolder">Accepted</p>
                    <% when "declined" %>
                      <p style="color: red; font-weight: bolder">Declined</p>
                    <% end %>
                </div>
                </div>
                </div>

                <div class='col-5'>
                  <p> USER INFORMATION </p>
                  <% if !booking.user.name %>
                    <p> Name: <strong> <%= booking.user.email.split('@').first.capitalize %></strong></p>
                  <% else  %>
                    <p> Name: <strong> <%= booking.user.name.capitalize %></strong>  </p>
                  <% end %>
                  <p> Email: <strong> <%= booking.user.email %></strong> </p>
                  <p> <i class="fas fa-star" style="color: #ffcd3c"></i> <%= booking.user.user_average_rating %></p>
                 </div>
                </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render 'new_booking_form' %>

app/views/bookings/show.html.erb
<div class="container show-container">
  <h1 class="main-header">My booking</h1>
  <div class="row show-row">
    <div class="col-lg-3 col-6">
      <div class="card-notdog-show mb-3">
        <img src=<%= cl_image_path @booking.notdog.photo.key, height: 500, width: 700, crop: :fill %> >
        <div class="card-notdog-infos-show">
          <div>
            <p class="text-black-50"><%= @booking.notdog.taxonomy_fantasy_name %> (<%= @booking.notdog.taxonomy_name %>)</p>
            <h2><%= link_to @booking.notdog.name, notdog_path(@booking.notdog) %></h2>
            <p><%= @booking.notdog.description %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="card p-3">
      <div class="col-log-4 details">
        <h2 class="text-left">Other details:</h2>
        <p>Owner: <%= @booking.notdog.owner.name %> </p>
        <p>Fantasy name: <%= @booking.notdog.taxonomy_fantasy_name %></p>
        <p>Location: <%= @booking.notdog.address %></p>
        <p>Total price: USD$<%= @booking.price %></p>
        <p>Start date: <%= @booking.start_date %></p>
        <p>End date: <%= @booking.end_date %></p>
        <div>
          <%= link_to "Add a Review", new_booking_review_path(@booking) %>
          <br>
          <%= link_to "Back to My Bookings", bookings_path %>
        </div>
         <div>
        <% if policy(@booking).destroy? %>
        <%= link_to "Delete this booking", booking_path(@booking), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }  %>
        <% end %>
      </div>
      </div>
      <div class="card-category" id="map-card"
      style="width: 25vw; height: 25vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">

      <div>
        <% unless @booking.end_date > Time.current %>
        <%= link_to @booking.owner != current_user ? "Add review for customer" : "Add a Review", new_booking_review_path(@booking), class: 'btn btn-primary' %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="card-category" id="map-card"
  style="width: 25vw; height: 25vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">

</div>
</div>
</div>