config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :bookings, only: [:show]
  end
  resources :notdogs do
    resources :bookings, only: [:new, :create]
    resources :messages, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [ :new, :create ]
  end
    get "my_notdogs", to: "notdogs#my_notdogs"
    get "my_booked", to: "bookings#my_booked"

    # buttons to accept/decline a booking
    # get "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    # get "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
    put "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    put "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
end

#               root GET    /                                                  pages#home
#    notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)             bookings#create
# new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)         bookings#new
#    notdog_messages POST   /notdogs/:notdog_id/messages(.:format)             messages#create
# new_notdog_message GET    /notdogs/:notdog_id/messages/new(.:format)         messages#new
# edit_notdog_message GET    /notdogs/:notdog_id/messages/:id/edit(.:format)   messages#edit
#            notdogs GET    /notdogs(.:format)                                 notdogs#index
#                    POST   /notdogs(.:format)                                 notdogs#create
#         new_notdog GET    /notdogs/new(.:format)                             notdogs#new
#        edit_notdog GET    /notdogs/:id/edit(.:format)                        notdogs#edit
#             notdog GET    /notdogs/:id(.:format)                             notdogs#show
#                    PATCH  /notdogs/:id(.:format)                             notdogs#update
#                    PUT    /notdogs/:id(.:format)                             notdogs#update
#                    DELETE /notdogs/:id(.:format)                             notdogs#destroy
#           bookings GET    /bookings(.:format)                                bookings#index
#       edit_booking GET    /bookings/:id/edit(.:format)                       bookings#edit
#            booking GET    /bookings/:id(.:format)                            bookings#show
#                    PATCH  /bookings/:id(.:format)                            bookings#update
#                    PUT    /bookings/:id(.:format)                            bookings#update


#                   Prefix Verb   URI Pattern                                  Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                     devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                    devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)               devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                    devise/passwords#update
#                          PUT    /users/password(.:format)                    devise/passwords#update
#                          POST   /users/password(.:format)                    devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                      devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                     devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                        devise/registrations#edit
#        user_registration PATCH  /users(.:format)                             devise/registrations#update
#                          PUT    /users(.:format)                             devise/registrations#update
#                          DELETE /users(.:format)                             devise/registrations#destroy
#                          POST   /users(.:format)                             devise/registrations#create
#                     root GET    /                                            pages#home
#          notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)       bookings#create
#       new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)   bookings#new
#                  notdogs GET    /notdogs(.:format)                           notdogs#index
#                          POST   /notdogs(.:format)                           notdogs#create
#               new_notdog GET    /notdogs/new(.:format)                       notdogs#new
#              edit_notdog GET    /notdogs/:id/edit(.:format)                  notdogs#edit
#                   notdog GET    /notdogs/:id(.:format)                       notdogs#show
#                          PATCH  /notdogs/:id(.:format)                       notdogs#update
#                          PUT    /notdogs/:id(.:format)                       notdogs#update
#                          DELETE /notdogs/:id(.:format)                       notdogs#destroy
#                 bookings GET    /bookings(.:format)                          bookings#index
#             edit_booking GET    /bookings/:id/edit(.:format)                 bookings#edit
#                  booking GET    /bookings/:id(.:format)                      bookings#show
#                          PATCH  /bookings/:id(.:format)                      bookings#update
#                          PUT    /bookings/:id(.:format)                      bookings#update
#          booking_reviews POST   /bookings/:booking_id/reviews(.:format)      reviews#create
#       new_booking_review GET    /bookings/:booking_id/reviews/new(.:format)  reviews#new

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer-copyright">
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i> By the "NO ENVIDIES MI PROGRESO SIN CONOCER MI SACRIFICIO" Team at LeWagon Batch #384 <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <% if user_signed_in? %>
    <%= link_to notdogs_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <% if current_user.notdogs.count > 0 %>
        <%= link_to "My Notdogs", my_notdogs_path , class: "nav-link" %>
        <%= link_to "Booking Requests", my_booked_path , class: "nav-link" %>
      <% end %>
      <% if current_user.bookings.count > 0 %>
        <%= link_to "View My Bookings", bookings_path , class: "nav-link" %>
      <% end %>
        <%= link_to "+ New Notdog", new_notdog_path , class: "nav-link" %>
        <li class="nav-item dropdown ml-2">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://www.jdevoto.cl/web/wp-content/uploads/2018/04/default-user-img.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <div class="navbar-text ml-2">
            <% if current_user.name.nil? %>
              <%= current_user.email.split('@').first.capitalize %>
            <% else  %>
              <%= current_user.name %>
            <% end %>
          </div>
      <% else %>
        <li class="nav-item d-flex">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="navbar-invisible-div"></div>