config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :bookings, only: [:show]
  end
  resources :notdogs do
    resources :bookings, only: [:new, :create]
    resources :messages, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:index]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [ :new, :create ]
  end
    get "my_notdogs", to: "notdogs#my_notdogs"
    get "my_booked", to: "bookings#my_booked"

    # buttons to accept/decline a booking
    # get "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    # get "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
    put "bookings/:booking_id/accept", to: "bookings#accept", as: "accept"
    put "bookings/:booking_id/decline", to: "bookings#decline", as: "decline"
end

#               root GET    /                                                  pages#home
#    notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)             bookings#create
# new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)         bookings#new
#    notdog_messages POST   /notdogs/:notdog_id/messages(.:format)             messages#create
# new_notdog_message GET    /notdogs/:notdog_id/messages/new(.:format)         messages#new
# edit_notdog_message GET    /notdogs/:notdog_id/messages/:id/edit(.:format)   messages#edit
#            notdogs GET    /notdogs(.:format)                                 notdogs#index
#                    POST   /notdogs(.:format)                                 notdogs#create
#         new_notdog GET    /notdogs/new(.:format)                             notdogs#new
#        edit_notdog GET    /notdogs/:id/edit(.:format)                        notdogs#edit
#             notdog GET    /notdogs/:id(.:format)                             notdogs#show
#                    PATCH  /notdogs/:id(.:format)                             notdogs#update
#                    PUT    /notdogs/:id(.:format)                             notdogs#update
#                    DELETE /notdogs/:id(.:format)                             notdogs#destroy
#           bookings GET    /bookings(.:format)                                bookings#index
#       edit_booking GET    /bookings/:id/edit(.:format)                       bookings#edit
#            booking GET    /bookings/:id(.:format)                            bookings#show
#                    PATCH  /bookings/:id(.:format)                            bookings#update
#                    PUT    /bookings/:id(.:format)                            bookings#update


#                   Prefix Verb   URI Pattern                                  Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                     devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                    devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)               devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                    devise/passwords#update
#                          PUT    /users/password(.:format)                    devise/passwords#update
#                          POST   /users/password(.:format)                    devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                      devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                     devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                        devise/registrations#edit
#        user_registration PATCH  /users(.:format)                             devise/registrations#update
#                          PUT    /users(.:format)                             devise/registrations#update
#                          DELETE /users(.:format)                             devise/registrations#destroy
#                          POST   /users(.:format)                             devise/registrations#create
#                     root GET    /                                            pages#home
#          notdog_bookings POST   /notdogs/:notdog_id/bookings(.:format)       bookings#create
#       new_notdog_booking GET    /notdogs/:notdog_id/bookings/new(.:format)   bookings#new
#                  notdogs GET    /notdogs(.:format)                           notdogs#index
#                          POST   /notdogs(.:format)                           notdogs#create
#               new_notdog GET    /notdogs/new(.:format)                       notdogs#new
#              edit_notdog GET    /notdogs/:id/edit(.:format)                  notdogs#edit
#                   notdog GET    /notdogs/:id(.:format)                       notdogs#show
#                          PATCH  /notdogs/:id(.:format)                       notdogs#update
#                          PUT    /notdogs/:id(.:format)                       notdogs#update
#                          DELETE /notdogs/:id(.:format)                       notdogs#destroy
#                 bookings GET    /bookings(.:format)                          bookings#index
#             edit_booking GET    /bookings/:id/edit(.:format)                 bookings#edit
#                  booking GET    /bookings/:id(.:format)                      bookings#show
#                          PATCH  /bookings/:id(.:format)                      bookings#update
#                          PUT    /bookings/:id(.:format)                      bookings#update
#          booking_reviews POST   /bookings/:booking_id/reviews(.:format)      reviews#create
#       new_booking_review GET    /bookings/:booking_id/reviews/new(.:format)  reviews#new

app/models/notdog.rb
class Notdog < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: 'user_id'
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :owner, :cost_per_day, :description, :name, :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews, through: :bookings, dependent: :destroy
  has_many :messages, dependent: :destroy
  validate :photo_present

  def photo_present
    unless photo.attached?
      photo.attach(io: File.open(Dir.getwd + "/app/assets/images/notdog-marker.png"), filename: "default.png", content_type: 'image/png')
    end
  end

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name, :taxonomy_category, :taxonomy_name, :address ],
    using: {
      tsearch: { prefix: true }
    }

  def average_score
    if !self.reviews.empty?
      user_score = self.reviews.pluck(:user_score)
      user_score.delete(nil)
      user_score.sum / user_score.length
    else
      []
    end
  end
end

app/controllers/notdogs_controller.rb
class NotdogsController < ApplicationController
  before_action :set_notdog, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: [:my_notdogs]

  def index
    if params[:query].present?
      sql_query = " \
      notdogs.taxonomy_name @@ :query \
      OR notdogs.taxonomy_category @@ :query \
      OR notdogs.address @@ :query \
      OR notdogs.name @@ :query \
      "
      @notdogs = policy_scope(Notdog).where(sql_query, query: "%#{params[:query]}%").geocoded
      @markers = @notdogs.map do |notdog|
        {
          lat: notdog.latitude,
          lng: notdog.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { notdog: notdog }),
          image_url: helpers.asset_url('notdog-marker.png')
        }
        end
        # No encuentra resultados para la query
      if @notdogs.empty?
        @notdogs = policy_scope(Notdog).order(name: :asc).geocoded
        @markers = @notdogs.map do |notdog|
          {
            lat: notdog.latitude,
            lng: notdog.longitude,
            infoWindow: render_to_string(partial: "info_window", locals: { notdog: notdog }),
            image_url: helpers.asset_url('notdog-marker.png')
          }
        end
      end
      # No hay query
    else
      @notdogs = policy_scope(Notdog).order(name: :asc).geocoded
      @markers = @notdogs.map do |notdog|
        {
          lat: notdog.latitude,
          lng: notdog.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { notdog: notdog }),
          image_url: helpers.asset_url('notdog-marker.png')
        }
      end
    end
  end

  def show
    @markers =
      [{
        lat: @notdog.latitude,
        lng: @notdog.longitude,
        # infoWindow: render_to_string(partial: "info_window", locals: { notdog: @notdog }),
        image_url: helpers.asset_url('notdog-marker.png')
      }]
    # Q&A
    booking_form
    @messages = @notdog.messages
    @reviews = @notdog.reviews
  end

  def new
    @notdog = Notdog.new
    authorize @notdog
  end

  def create
    @notdog = Notdog.new(notdog_params)
    @notdog.taxonomy_category = notdog_params[:taxonomy_category].drop(1).join(", ")
    @notdog.owner = current_user
    authorize @notdog
    if @notdog.save
      redirect_to @notdog
    else
      render :new
    end
  end

  def edit; end

  def update
    @notdog.update(notdog_params)
    if @notdog.save
      redirect_to @notdog
    else
      render :edit
    end
  end

  def destroy
    @notdog.destroy
    redirect_to notdogs_path
  end

  def my_notdogs
    @notdogs = current_user.notdogs
  end

  def booking_form
    @booking = Booking.new
    @notdog = Notdog.find(params[:id].to_i)
    @booking.notdog = @notdog
    authorize @notdog
    authorize @booking
  end

  private

  def notdog_params
    # estos parametros se usan tanto para crear como para updatear un notdog
    params.require(:notdog).permit(:name, :cost_per_day, :description, :address, :taxonomy_name, :taxonomy_fantasy_name, :photo, taxonomy_category: [])
  end

  def set_notdog
    @notdog = Notdog.find(params[:id])
    authorize @notdog
  end
end

app/views/notdogs/_form.html.erb
<div class="container">
    <div class="form-group">
      <%= simple_form_for @notdog do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, placeholder: "Nombre" %>
      <%= f.input :description, as: :text, placeholder: "Describe tu mascota" %>
      <%= f.input :cost_per_day %>
      <%= f.input :address, placeholder: "Dirección" %>
      <%= f.input :taxonomy_name, :label => "Pet name" %>
      <%= f.input :taxonomy_fantasy_name, :label => "Fantasy name" %>
      <%= f.input :taxonomy_category, :label => "Category" %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
    </div>
</div>

app/views/notdogs/_info_window.html.erb
<div class="card-trip">
  <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselIndicators" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active mt-2">
          <img src=<%= cl_image_path notdog.photo.key, height: 150, width: 210, crop: :fill %>>
        </div>
        <div class="carousel-item mt-2">
          <img src=<%= cl_image_path notdog.photo.key, height: 150, width: 210, crop: :fill %>>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="card-notdog-infos">
    <div>
      <h2><%= notdog.name %></h2>
      <p><%= notdog.address %></p>
    </div>
  </div>
</div>

app/views/notdogs/_messages.html.erb
<!-- Messages Q&A -->
<div class="container show-container">
  <div class="row show-row">

    <div class="messages">
      <h2>Q&A</h2>


        <% if policy(@notdog).cannot_ask_itself_a_question? %>

        <%= link_to "Unsure? Ask a question", new_notdog_message_path(@notdog) %>
        <% end %>

        <% @messages.each do |message| %>

        <div class="interaction">

            <div class="message-body border-top px-2">
              <%= message.body %>
              <div class="message-body-infos">
                <span class="created-at">(<%= time_ago_in_words(message.created_at, include_seconds: true) %> ago) </span>
                <% if policy(message).update? %>
                  <%= link_to "Reply", edit_notdog_message_path(@notdog, message) %>
                <% end %>

                <% if policy(message).destroy? %>
                  | <%= link_to "Delete question", notdog_message_path(@notdog, message), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }  %>
                <% end %>

              </div>
            </div>

            <!-- Answer logic -->
            <% if message.answer.present? %>
              <div class="message-answer pr-2">
                <div>
                  <i class="fas fa-level-up-alt flecha-respuesta"></i>  <%= message.answer %>
                </div>
                <div class="message-answer-infos">
                  <span class="updated-at">(<%= time_ago_in_words(message.updated_at, include_seconds: true) %> ago) </span>
                </div>
              </div>
            <% end %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/notdogs/_new_edit_form.html.erb
<div class="container mt-5">
    <div class="form-group">
      <%= simple_form_for(@notdog, remote: true) do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, placeholder: "Pet Name" %>
      <%= f.input :description, as: :text, placeholder: "Describe tu mascota" %>
      <%= f.input :cost_per_day %>
      <%= f.input :address, placeholder: "Dirección" %>
      <%= f.input :taxonomy_name, :label => "Species name (Bull, Shark, Giraffe, etc.)" %>
      <%= f.input :taxonomy_fantasy_name, :label => "Fantasy name (Horn Doggo, Bitey Water Doggo, Tall Doggo, etc.)" %>
      <%= f.input :taxonomy_category, :label => "Category", as: :check_boxes, collection: ['Terrestre', 'Acuático', 'Aéreo', 'Carnivoro', 'Herbívoro', 'Insectívoro'], wrapper: :vertical_collection_inline %>
      <%= f.input :photo, as: :file, required: true %>
      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
    </div>
</div>

app/views/notdogs/_new_form.html.erb
<div class="container">
    <div class="form-group">
      <%= simple_form_for @notdog do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, placeholder: "Nombre" %>
      <%= f.input :description, as: :text, placeholder: "Describe tu mascota" %>
      <%= f.input :cost_per_day %>
      <%= f.input :address, placeholder: "Dirección" %>
      <%= f.input :taxonomy_name, :label => "Pet name" %>
      <%= f.input :taxonomy_fantasy_name, :label => "Fantasy name" %>
      <%= f.input :taxonomy_category, :label => "Category" %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
    </div>
</div>

app/views/notdogs/_search_bar_index.html.erb
<div class="row d-flex col-lg">
  <%= form_tag notdogs_path, method: :get, class: "d-flex flex-nowrap justify-content-left w-100" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control mb-3",
      placeholder: "Search by city, Notdog category or habitat"%>
    <%= submit_tag "Search", class: "btn btn-primary", style: "height: 38px" %>
  <% end %>
</div>

app/views/notdogs/edit.html.erb
<div class='container'>
  <%= render 'new_edit_form' %>
</div>

app/views/notdogs/index.html.erb
<div id="main-index-div">
  <div class="cards mt-0">
    <div>
      <h1 class="main-header mb-0">Welcome to a unique experience!</h1>
      <p class="pb-3 mb-0">We have <%= pluralize(@notdogs.count.round, "notdog") %> available for booking!</p>
      <%= render "search_bar_index" %>
    </div>
    <% @notdogs.each do |notdog| %>
    <%= link_to notdog_path(notdog) do %>
        <div class="card-notdog my-0 py-3 border-top">
          <img class="card-notdog-img border", src=<%= cl_image_path notdog.photo.key, height: 400, width: 500, crop: :fill %> >
          <div class="card-notdog-infos">

            <div>
              <p class="text-black-50"><%= notdog.taxonomy_fantasy_name %> (<%= notdog.taxonomy_name %>)</p>
            <h2><%= notdog.name %></h2>
              <% if notdog.description.length > 30 %>
                <p><%= notdog.description[0...30] %>...</p>
              <% else %>
                <%= notdog.description %>
              <% end %>
              <% if !notdog.reviews.empty? %>
              <div class="d-flex flex-nowrap align-items-center" >
                <% notdog.average_score.times do %>
                <i class="fas fa-star" style="color: #ffcd3c"></i>
                  <% end %>
                <% (5 - notdog.average_score).times do %>
                  <i class="far fa-star" style="color: #ffcd3c"></i>
                <% end %>
                <p class="text-black-50 ml-1">(<%= notdog.reviews.count %>)</p>
              </div>
              <% else %>
                <p>No reviews yet <i class="far fa-frown" style="color: #ffcd3c"></i></p>
              <% end %>

            </div>
          <% if notdog.owner.photo.attached? %>
              <%= cl_image_tag notdog.owner.photo.key, class: "card-notdog-user avatar-bordered" %>
            <% else %>
              <%= image_tag "https://www.jdevoto.cl/web/wp-content/uploads/2018/04/default-user-img.jpg", class: "card-notdog-user avatar-bordered" %>
            <% end %>
            <p class="card-notdog-pricing"><strong>USD$<%= notdog.cost_per_day %></strong>/day</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>
</div>

app/views/notdogs/my_notdogs.html.erb
<div class="container mt-5">
  <h2 class="main-header">My Notdogs</h2>
   <% @notdogs.each do | notdog | %>
      <div class="card-notdog my-3 d-flex">
        <img class="card-notdog-img", src=<%= cl_image_path notdog.photo.key, height: 400, width: 500, crop: :fill %> >
        <div class="card-notdog-infos">
          <%= link_to notdog.name, notdog_path(notdog), class: "main-header" %>
        </div>
        <div class="d-flex align-items-end m-3">
          <%= link_to "", notdog_path(notdog), method: :delete, data: { confirm: 'Are you certain you want to delete this Notdog?' }, class: "fas fa-trash-alt px-3" %>
          <%= link_to "", edit_notdog_path(notdog), class: "fas fa-pencil-alt" %>
        </div>
      </div>
    <% end %>
</div>

app/views/notdogs/new.html.erb
<div class='container'>
  <%= render 'new_form' %>
</div>

app/views/notdogs/show.html.erb
<div class="container show-container">

      <div class="d-flex wrap mt-3 show-header">
        <h2 class="orange"><%= @notdog.name %></h2><h2 class="text-black-50 ml-2"> - <%= @notdog.taxonomy_fantasy_name %> (<%= @notdog.taxonomy_name %>)</h2>
      </div>
      <div class="d-flex flex-nowrap align-items-center justify-content-between mb-3" >
        <div class="d-flex align-items-center">
        <% if !@notdog.reviews.empty? %>

          <% @notdog.average_score.times do %>
            <i class="fas fa-star" style="color: #ffcd3c"></i>
          <% end %>
          <% (5 - @notdog.average_score).times do %>
            <i class="far fa-star" style="color: #ffcd3c"></i>
          <% end %>
            <p class="text-black-50 ml-1 mb-0">(<%= @notdog.reviews.count %>)</p>

        <% else %>
          <p class="m-0">No reviews yet <i class="far fa-frown" style="color: #ffcd3c"></i></p>
        <% end %>
        <p class="my-0 mx-2">·</p>
          <p class="ml-1 mb-0"><%= @notdog.address %></p>
        </div>
        <%= link_to notdogs_path, class: "orange" do %>
          Back to home <i class="fa fa-home"></i>
        <% end %>
      </div>
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8 col-12 mx-0">
        <div class="show-notdog-img" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @notdog.photo.key, height: 500, width: 700, crop: :fill %>)";></div>
      </div>
      <div class="col-lg-4 col-12 mx-0">
        <div class="d-flex card show-booking-card p-3">
        <div class="d-flex justify-content-between align-items-top">
          <p class="flex-grow-1"><strong>$<%= @notdog.cost_per_day %></strong> / day</p>
          <% if !@notdog.reviews.empty? %>
            <%= link_to notdog_reviews_path(@notdog) do %>
              <div class="d-flex align-items-center">
                <% @notdog.average_score.times do %>
                  <i class="fas fa-star" style="color: #ffcd3c"></i>
                <% end %>
                <% (5 - @notdog.average_score).times do %>
                  <i class="far fa-star" style="color: #ffcd3c"></i>
                <% end %>
                <p class="text-black-50 ml-1 mb-0">(<%= @notdog.reviews.count %>)</p>
              </div>
            <% end %>
          <% else %>
            <p>No reviews yet <i class="far fa-frown" style="color: #ffcd3c"></i></p>
          <% end %>
        </div>
        <hr>

        <div class="notdog-show-information">
          <div class="d-flex">
            <p><%= @notdog.description %></p>
          </div>
          <div>
            <p>Owner: <%= @notdog.owner.name %></p>
          </div>
        </div>
        <hr>
        <div>
          <% if @notdog.owner != current_user %>
            <%= render './bookings/new_booking_form' %>
          <% end %>
          <% if policy(@notdog).destroy? %>
            Owner maintenance:
            <%= link_to "", notdog_path(@notdog), method: :delete, data: { confirm: 'Are you certain you want to delete this Notdog?' }, class: "fas fa-trash-alt pl-3 orange" %>
            <%= link_to "", edit_notdog_path(@notdog), class: "fas fa-pencil-alt orange pl-3" %>
          <% end %>
        </div>
      </div>
    </div>
    <div id="map-card"
          class="m-3 rounded-lg"
          style="width: 100vw; height: 25vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
    </div>
  </div>
</div>



<%= render "messages" %>